[package]
name = "hello_movement"
version = "1.0.0"
edition = "2025.alpha"

[dependencies]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
counter = "0xYourAddress"
